default: &default
  encoding: unicode
  username: postgres
  password: password
  pool: 50
  adapter: postgresql
  host: localhost

development:
  <<: *default
  database: weather_aggregator_dev

test:
  <<: *default
  database: weather_aggregator_test

production:
  <<: *default
  password: <%= ENV["WA_DATABASE_PASSWORD"] %>
  database: weather_aggregator_prod
