default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  password: password
  host: localhost
  pool: 50

development:
  <<: *default
  database: weather_aggregator_dev

test:
  <<: *default
  database: weather_aggregator_test

production:
  <<: *default
  database: weather_aggregator_prod
