# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 35ba8378521a9ae6f071492d4c9617cbeabb91e53e886f52e956f38c4c46f3bcbe43580f03094b50589cb2f0ce565de1b6de2e3fd9f9ab3971e790a4acfcde52

test:
  secret_key_base: d8c9ca7b7d4101aa936cd426ad4b66b8cbd36c5538ba477f30996fe01047bfc397427118134ee0292712ecf0da1a71cdd9d81452dd703e21933e7d4a12885cd4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
